spring:
  profiles:
    active: ${APPLICATION_PROFILE:local}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  liquibase:
    change-log: classpath:db/db.changelog.xml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54320}/${DB_NAME:asfosis_app_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

springdoc:
  api-docs:
    path: /api-docs

application:
  default-admin:
    username: ${DEFAULT_ADMIN_USERNAME}
    password: ${DEFAULT_ADMIN_PASSWORD}
    email: ${DEFAULT_ADMIN_EMAIL}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: 600000
    refresh-expiration: 1200000

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
